### ISSUE TITLE
Encode inference vs training in node types

### ISSUE THREAD

**Issue by dowobeha** [amunmt/marian#22]
This is being worked on in the Issue22 branch.

**Comment by dowobeha** [comment]
Code has been refactored within the Issue22 branch. Code compiles, but there is a runtime error involving Tensor allocation.

For example, when running ./test_nodes:

`
terminate called after throwing an instance of 'util::Exception'
  what():  /home/lanes/Marian/src/tensor.h:403 in const marian::Shape& marian::Tensor::shape() const threw util::Exception because `!pimpl_'.
Tensor has not been allocated

Program received signal SIGABRT, Aborted.
0x00007fffea7d15f7 in raise () from /lib64/libc.so.6
Missing separate debuginfos, use: debuginfo-install glibc-2.17-106.el7_2.8.x86_64 libgcc-4.8.5-4.el7.x86_64 libstdc++-4.8.5-4.el7.x86_64
(gdb) bt
#0  0x00007fffea7d15f7 in raise () from /lib64/libc.so.6
#1  0x00007fffea7d2ce8 in abort () from /lib64/libc.so.6
#2  0x00007fffeb0d69d5 in __gnu_cxx::__verbose_terminate_handler() () from /lib64/libstdc++.so.6
#3  0x00007fffeb0d4946 in ?? () from /lib64/libstdc++.so.6
#4  0x00007fffeb0d4973 in std::terminate() () from /lib64/libstdc++.so.6
#5  0x00007fffeb0d4b93 in __cxa_throw () from /lib64/libstdc++.so.6
#6  0x0000000000411246 in marian::Tensor::shape (this=this@entry=0x7fffffffdff0) at /home/lanes/Marian/src/tensor.h:403
#7  0x00000000004121e0 in operator() (__closure=<optimized out>) at /home/lanes/Marian/src/expression_operators.h:147
#8  std::_Function_handler<float (), std::shared_ptr<marian::DifferentiableNode> marian::mean<marian::keywords::Keyword<2232387322u, int> >(std::shared_ptr<marian::DifferentiableNode>, marian::keywords::Keyword<2232387322u, int>)::{lambda()#1}>::_M_invoke(std::_Any_data const&) (__functor=...) at /usr/include/c++/4.8.2/functional:2056
#9  0x0000000000479347 in operator() (this=0x7fffffffe070) at /usr/include/c++/4.8.2/functional:2471
#10 marian::ExpressionGraphNode::allocate (this=0x16763190, batchSize=<optimized out>) at /home/lanes/Marian/src/node.cu:27
#11 0x000000000041dec9 in marian::ExpressionGraph::forward (this=0x16762170, batch=std::shared_ptr (count 2, weak 0) 0x8280790) at /home/lanes/Marian/src/expression_graph.h:120
#12 0x0000000000407914 in main (argc=<optimized out>, argv=<optimized out>) at /home/lanes/Marian/src/test_nodes.cu:77
`
