### ISSUE TITLE
tensor_test segfaults

### ISSUE THREAD

**Issue by kpu** [amunmt/marian#32]
On zisa:

```
Thread 1 "tensor_test" received signal SIGSEGV, Segmentation fault.
spdlog::logger::_log_if_enabled (lvl=spdlog::level::info, this=0x0)
    at /home/heafield/marian/src/3rd_party/spdlog/details/logger_impl.h:68
68          return details::line_logger(this, lvl, should_log(lvl));
(gdb) bt
#0  spdlog::logger::_log_if_enabled (lvl=spdlog::level::info, this=0x0) at /home/heafield/marian/src/3rd_party/spdlog/details/logger_impl.h:68
#1  spdlog::logger::info (this=<optimized out>) at /home/heafield/marian/src/3rd_party/spdlog/details/logger_impl.h:213
#2  marian::TensorAllocator::reserve (this=this@entry=0x73b2f0, elements=<optimized out>)
    at /home/heafield/marian/src/tensors/tensor_allocator.h:99
#3  0x0000000000413001 in marian::TensorAllocator::checkSpace (
    shape=<error reading variable: access outside bounds of object referenced via synthetic pointer>, this=0x73b2f0)
    at /home/heafield/marian/src/tensors/tensor_allocator.h:84
#4  marian::TensorAllocator::allocate (this=0x73b2f0, t=std::shared_ptr (empty) 0x0, shape=...)
    at /home/heafield/marian/src/tensors/tensor_allocator.h:127
#5  0x00000000004053a6 in main () at /home/heafield/marian/src/test/tensor_test.cu:21
```

Logger isn't initialized properly?

**Comment by emjotde** [comment]
Fixed.
